### ISSUE TITLE
Banjax should log or otherwise warn when it is failing to load

### ISSUE THREAD

**Issue by nosmo** [equalitie/banjax#12]
Banjax doesn't log when configuration files are invalid, it just silently fails. Banjax should log when it's successfully loaded, how many rules it has loaded (for example - it could be another metric to indicate that it has successfully loaded the configuration file) and indicate when it has failed to load a log file and, if possible, why and where in the configuration file it has failed.

**Comment by inetic** [comment]
Done, as described in https://redmine.equalit.ie/issues/2090
