### ISSUE TITLE
Reloading of configs? 

### ISSUE THREAD

**Issue by nosmo** [equalitie/banjax#21]
We currently need to restart Banjax in order for new rules to take effect - is there a way that Banjax could add a handler for reloading the config? I'd like to think that ATS implements a way of plugins being notified of a traffic_line -x.

**Comment by oschaaf** [comment]
@nosmo That is possible. You need `TSMgmtUpdateRegister`
e.g. https://github.com/apache/trafficserver/blob/master/plugins/gzip/gzip.cc#L788

**Comment by nosmo** [comment]
This works now <3.
