### ISSUE TITLE
Banjax cannot be built on Debian 7

### ISSUE THREAD

**Issue by nosmo** [equalitie/banjax#29]
Until we upgrade across the Deflect network, banjax *must* be buildable on Debian 7. At the moment building Banjax fails with this error: 

```
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
```

**Comment by vmon** [comment]
Did you try ./autogen.sh at the begining (see redmine ticket). It worked for me on debian 7.
