### ISSUE TITLE
Unable to match empty user-agent in regex banning rules

### ISSUE THREAD

**Issue by kheops2713** [equalitie/banjax#35]
Setting the following rule:

```
- rule: mywebsite_dos_no_ua
  regex: '^GET\ .*mywebsite\.org\ $'
  interval: 1
  hits_per_interval: 0
```

is never matched, even though `traffic.out` reports this:

```
Examining GET http:/// mywebsite.org  for banned matches
```

Notice the double space in the log message, indicating a blank user-agent. According to [the source](https://github.com/equalitie/banjax/blob/master/src/transaction_muncher.cpp#L199), putting a final whitespace and `$` should match an empty UA. But the rule never gets matched.

**Comment by inetic** [comment]
Note: this isse is also referenced in redmine as #4487

**Comment by inetic** [comment]
I wrote a test for this issue [here](https://github.com/equalitie/banjax/commit/c23fbec4145e5c7921ef669353f46e360efec0aa#diff-ead0871009672d4e46d1a9140d8c1549R164). But it passes with success. Someone (@vmon?) has probably already fixed it(?).

@kheops2713, when you get a time, can you please check whether you're still seeing this on your side?

**Comment by graphiclunarkid** [comment]
I belive this is done.
