### ISSUE TITLE
base64 encoder assert

### ISSUE THREAD

**Issue by oschaaf** [equalitie/banjax#8]
Last week, I saw this assert trigger sometimes in ChallengeManager::base64_decode()

https://github.com/equalitie/banjax/blob/oschaaf-sanitize/src/challenge_manager.cpp#L450

@vmon 
Was that known? Is it fixed? 
The pull I just made moves this code, but it remains identical AFAICT.
I just want to make sure that I'm not overlooking a minor fix here, and re-introduce the assert.

**Comment by inetic** [comment]
The link is no longer valid and the function ChallengeManager::base64_decode() no longer exist in the code. Given this is quite old and lacking information I'm going to close it.

When the assert is triggered again, please reopen it or create a new issue.
